library(testthat)
source('rorranking/R/rorUtils.R')
source('rorranking/R/hierarchyUtils.R')
source('rorranking/R/extremeRankingAnalysis.R')
source('rorranking/R/findNecessaryAndPossiblePreferenceRelations.R')
source('rorranking/R/preferentionalReducts.R')

print('extreme ranking analysis:')
test_file('rorranking/inst/tests/eraTests.R')
print('finding relations')
test_file('rorranking/inst/tests/relationsTest.R')
print('finding reducts for nec relations')
test_file('rorranking/inst/tests/relationsReductsTest.R')
print('finding rank related reducts')
test_file('rorranking/inst/tests/ranksReductsTest.R')
print('DONE')
