library(testthat)
source('rorUtils.R')
source('hierarchyUtils.R')
source('extremeRankingAnalysis.R')
source('findNecessaryAndPossiblePreferenceRelations.R')
source('preferentionalReducts.R')

print('extreme ranking analysis:')
test_file('tests/eraTests.R')
print('finding relations')
test_file('tests/relationsTest.R')
print('finding reducts for nec relations')
test_file('tests/relationsReductsTest.R')
print('finding rank related reducts')
test_file('tests/ranksReductsTest.R')
print('DONE')
